copy %1\BoogieAbsInt.dll .
copy %1\BoogieAbsInt.pdb .
copy %1\BoogieBasetypes.dll .
copy %1\BoogieBasetypes.pdb .
copy %1\BoogieCodeContractsExtender.dll .
copy %1\BoogieCodeContractsExtender.pdb .
copy %1\BoogieConcurrency.dll .
copy %1\BoogieConcurrency.pdb .
copy %1\BoogieCore.dll .
copy %1\BoogieCore.pdb .
copy %1\BoogieExecutionEngine.dll .
copy %1\BoogieExecutionEngine.pdb .
copy %1\BoogieGraph.dll .
copy %1\BoogieGraph.pdb .
copy %1\BoogieHoudini.dll .
copy %1\BoogieHoudini.pdb .
copy %1\BoogieModel.dll .
copy %1\BoogieModel.pdb .
copy %1\BoogieParserHelper.dll .
copy %1\BoogieParserHelper.pdb .
copy %1\Provers.SMTLib.dll .
copy %1\Provers.SMTLib.pdb .
copy %1\BoogieVCExpr.dll .
copy %1\BoogieVCExpr.pdb .
copy %1\BoogieVCGeneration.dll .
copy %1\BoogieVCGeneration.pdb .
REM ------ other boogie files
copy %1\boogie.exe .
copy %1\boogie.pdb .
copy %1\BVD.exe .
copy %1\BVD.pdb .
copy %1\BoogieDoomed.dll .
copy %1\BoogieDoomed.pdb .
copy %1\BoogiePredication.dll .
copy %1\BoogiePredication.pdb .
