cp $1/AbsInt.dll .
cp $1/AbsInt.pdb .
cp $1/Basetypes.dll .
cp $1/Basetypes.pdb .
cp $1/CodeContractsExtender.dll .
cp $1/CodeContractsExtender.pdb .
cp $1/Concurrency.dll .
cp $1/Concurrency.pdb .
cp $1/Core.dll .
cp $1/Core.pdb .
cp $1/ExecutionEngine.dll .
cp $1/ExecutionEngine.pdb .
cp $1/Graph.dll .
cp $1/Graph.pdb .
cp $1/Houdini.dll .
cp $1/Houdini.pdb .
cp $1/Model.dll .
cp $1/Model.pdb .
cp $1/ParserHelper.dll .
cp $1/ParserHelper.pdb .
cp $1/Provers.SMTLib.dll .
cp $1/Provers.SMTLib.pdb .
cp $1/VCExpr.dll .
cp $1/VCExpr.pdb .
cp $1/VCGeneration.dll .
cp $1/VCGeneration.pdb .
cp $1/boogie.exe .
cp $1/boogie.pdb .
cp $1/BVD.exe .
cp $1/BVD.pdb .
cp $1/Doomed.dll .
cp $1/Doomed.pdb .
cp $1/Predication.dll .
cp $1/Predication.pdb .
