configuration=$1
./runonetest.sh $configuration t1.bpl "/traceSlicing" ""
./runonetest.sh $configuration t2_err.bpl "/traceSlicing" ""
./runonetest.sh $configuration t3_err.bpl "/traceSlicing" ""
./runonetest.sh $configuration t4.bpl "/traceSlicing" ""
./runonetest.sh $configuration t5.bpl "/traceSlicing" ""
./runonetest.sh $configuration t6.bpl "/traceSlicing" ""
./runonetest.sh $configuration t7.bpl "/traceSlicing" ""
./runonetest.sh $configuration t8.bpl "/traceSlicing" ""
./runonetest.sh $configuration t9.bpl "/traceSlicing" ""
./runonetest.sh $configuration pruned.bpl "/traceSlicing" ""
./runonetest.sh $configuration empty_forall.bpl "/traceSlicing" ""
./runonetest.sh $configuration null.bpl "/traceSlicing" ""
./runonetest.sh $configuration generalize.bpl "/traceSlicing" ""
./runonetest.sh $configuration rec.bpl "/traceSlicing" ""
./runonetest.sh $configuration eeSlice3.bpl "/traceSlicing" ""
./runonetest.sh $configuration eeSlice4.bpl "/traceSlicing" ""
./runonetest.sh $configuration eeSlice5.bpl "/traceSlicing" ""
./runonetest.sh $configuration eeSlice6.bpl "/traceSlicing" ""
./runonetest.sh $configuration eeSlice61.bpl "/traceSlicing" ""
./runonetest.sh $configuration eeSlice2.bpl "/traceSlicing /repeatEEWithControlFlow" ""
./runonetest.sh $configuration type_alias.bpl "/traceSlicing" ""
./runonetest.sh $configuration delayed_initialization.bpl "/traceSlicing" "/unknownType:Ref /delayInitialization"
